Repository puppetlabs/puppetlabs-docker, pull requests merged in 2019-09, with the labels that each got.

#527 (maint) Add a codeowners file
  CODEOWNERS
Labels: maintenance

#523 Fix multiple additional flags for docker_network
  lib/puppet/provider/docker_network/ruby.rb
  spec/unit/lib/puppet/type/docker_network_spec.rb
Labels: bugfix

#525 pdksync - Add support on Debian10
  metadata.json
Labels: feature
