Repository puppetlabs/puppetlabs-docker, pull requests merged in 2019-08, with the labels that each got.

#509 Add new Docker Swarm Tasks (node ls, rm, update; service scale)
  tasks/node_ls.json
  tasks/node_ls.rb
  tasks/node_rm.json
  tasks/node_rm.rb
  tasks/node_update.json
  tasks/node_update.rb
  tasks/service_scale.json
  tasks/service_scale.rb
Labels: feature

#520 :bug: Fix wrong service detach handling
  lib/puppet/parser/functions/docker_service_flags.rb
Labels: bugfix

#514 Fix aliased plugin names
  lib/puppet/parser/functions/docker_plugin_enable_flags.rb
  manifests/plugin.pp
  spec/defines/plugin_spec.rb
Labels: bugfix, needs-tests
