Repository puppetlabs/puppetlabs-docker, pull requests merged in 2019-11, with the labels that each got.

#549 Add option for RemainAfterExit
  manifests/run.pp
  templates/etc/systemd/system/docker-run.erb
Labels: feature

#544 Allow defining the name of the docker-compose symlink
  manifests/compose.pp
  manifests/params.pp
Labels: bugfix

#553 Fix error does not show when image:tag does not exists (#552)
  manifests/image.pp
  spec/defines/image_spec.rb
  spec/defines/image_windows_spec.rb
Labels: bugfix

#555 (MODULES-10120) enable simplecov; update to PDK 1.14.1; minor cleanups
  .rubocop.yml
  .sync.yml
  .travis.yml
  .vscode/extensions.json
  Gemfile
  Rakefile
  metadata.json
  spec/default_facts.yml
Labels: maintenance
