Repository puppetlabs/puppetlabs-docker, pull requests merged in 2020-08, with the labels that each got.

#648 [MODULES-10734] - improve params detection on docker::run
  lib/puppet/parser/functions/docker_params_changed.rb
  lib/puppet/parser/functions/docker_run_flags.rb
  manifests/run.pp
  spec/acceptance/docker_params_changed_spec.rb
Labels: bugfix

#642 Update params.pp
  manifests/params.pp
Labels: maintenance

#650 Merge back for Release v.3.11.0
  CHANGELOG.md
  REFERENCE.md
  metadata.json
Labels: maintenance

#652 [IAC-1056] - Add acceptance test for prepare_service_only param
  manifests/run.pp
  spec/acceptance/docker_spec.rb
  templates/docker-run-start.erb
Labels: feature, maintenance

#653 Fix syntax for puppet 4 support
  manifests/registry.pp
Labels: bugfix, maintenance

#654 (IAC-982) - Remove inappropriate terminology
  .github/workflows/release.yml
  .github/workflows/weekly.yml
  Gemfile
  README.md
  REFERENCE.md
  Rakefile
  lib/puppet/type/docker_network.rb
  metadata.json
  spec/acceptance_swarm/swarm_spec.rb
  tasks/swarm_token.json
Labels: feature
