Repository puppetlabs/puppetlabs-docker, pull requests merged in 2020-04, with the labels that each got.

#477 Allow bypassing curl package ensure if needed
  README.md
  manifests/compose.pp
  manifests/machine.pp
  manifests/params.pp
Labels: feature, needs-tests

#585 [IAC-291] Convert acceptance tests to Litmus
  .fixtures.yml
  .github/workflows/release.yml
  .github/workflows/ubuntu16_pr.yaml
  .github/workflows/ubuntu18_pr.yaml
  .github/workflows/weekly.yml
  .gitignore
  Gemfile
  README.md
  provision.yaml
  spec/acceptance/compose_v3_spec.rb
  spec/acceptance/docker_custom_source_spec.rb
  spec/acceptance/docker_full_spec.rb
  spec/acceptance/docker_spec.rb
  spec/acceptance/network_spec.rb
  spec/acceptance/nodesets/default.yml
  spec/acceptance/nodesets/pooler/centos7.yml
  spec/acceptance/nodesets/pooler/debian-8.yml
  spec/acceptance/nodesets/pooler/debian-9.yml
  spec/acceptance/nodesets/pooler/rhel7.yml
  spec/acceptance/nodesets/pooler/ubuntu-1404.yml
  spec/acceptance/nodesets/pooler/ubuntu-1604.yml
  spec/acceptance/nodesets/pooler/ubuntu-1610.yml
  spec/acceptance/nodesets/pooler/ubuntu-1804.yml
  spec/acceptance/nodesets/pooler/win-2016.yml
  spec/acceptance/nodesets/vagrant/centos-70-x64.yml
  spec/acceptance/nodesets/vagrant/debian-81-x64.yml
  spec/acceptance/nodesets/vagrant/ubuntu-1404-x64.yml
  spec/acceptance/nodesets/vagrant/ubuntu-1604-x64.yml
  spec/acceptance/plugin_spec.rb
  spec/acceptance/stack_spec.rb
  spec/acceptance/volume_spec.rb
  spec/spec_helper_acceptance.rb
  spec/spec_helper_acceptance_local.rb
Labels: feature

#599 [MODULES-10628] Update documentation for docker volume and set options as parameter
  README.md
  lib/puppet/type/docker_volume.rb
  spec/unit/lib/puppet/type/docker_volume_spec.rb
Labels: bugfix

#601 Fix `docker_network` unit tests
  spec/unit/lib/puppet/provider/docker_network_spec.rb
Labels: maintenance

#603 Enforce TLS1.2 on Windows; minor fixes for RH-based testing
  spec/acceptance/compose_v3_spec.rb
  spec/acceptance/machine_spec.rb
  templates/windows/check_powershell_provider.ps1.erb
  templates/windows/install_powershell_provider.ps1.erb
Labels: bugfix

#604 Release prep version 3.10.0
  CHANGELOG.md
  REFERENCE.md
  metadata.json
Labels: maintenance

#605 Release Mergeback v.3.10.0
  CHANGELOG.md
  REFERENCE.md
  metadata.json
Labels: maintenance
