Repository puppetlabs/puppetlabs-docker, pull requests merged in 2020-12, with the labels that each got.

#687 pdksync - (feat) - Bump Puppet boundary
  metadata.json
Labels: feature

#697 (MAINT) - Mergeback v3.13.0
  CHANGELOG.md
  REFERENCE.md
  metadata.json
Labels: maintenance

#698 docker complaining: change HOME var to /root
  lib/puppet/provider/docker_compose/ruby.rb
  lib/puppet/provider/docker_network/ruby.rb
  lib/puppet/provider/docker_stack/ruby.rb
  lib/puppet/provider/docker_volume/ruby.rb
Labels: bugfix

#700 (MAINT) Fix Debian version entries in metadata
  metadata.json
Labels: maintenance
