Repository puppetlabs/puppetlabs-docker, pull requests merged in 2021-02, with the labels that each got.

#705 (IAC-1218) - docker_params_changed should be run by agent
  lib/puppet/functions/docker_params_changed.rb
  manifests/run.pp
  spec/acceptance/docker_params_changed_spec.rb
  spec/acceptance/docker_spec.rb
  spec/defines/run_spec.rb
  spec/helper/get_docker_params_changed.rb
  spec/shared_examples.rb
  spec/shared_examples/run.rb
  spec/spec_helper_acceptance_local.rb
Labels: bugfix

#710 Release prep for version v3.13.1
  CHANGELOG.md
  REFERENCE.md
  metadata.json
Labels: maintenance

#711 Revert "Release prep for version v3.13.1"
  CHANGELOG.md
  REFERENCE.md
  metadata.json
Labels: maintenance

#712 Release prep v3.13.1
  CHANGELOG.md
  REFERENCE.md
  metadata.json
Labels: maintenance

#713 (IAC-1410) Release mergeback v3.13.1
  CHANGELOG.md
  REFERENCE.md
  metadata.json
Labels: maintenance

#718 pdksync - Remove Puppet 5 from testing and bump minimal version to 6.0.0
  .github/workflows/auto_release.yml
  .rubocop.yml
  .travis.yml
  metadata.json
  provision.yaml
Labels: backwards-incompatible

#722 (maint) Update major dependencies prior to release
  metadata.json
Labels: maintenance

#723 (maint) Update reboot dependency
  metadata.json
Labels: maintenance
