Repository puppetlabs/puppetlabs-docker, pull requests merged in 2021-06, with the labels that each got.

#753 pdksync - (maint) PDKSync - PDK Update
  .github/workflows/auto_release.yml
  .github/workflows/release.yml
  .github/workflows/spec.yml
  .pdkignore
  metadata.json
Labels: maintenance

#752 Allow force update non-latest tagged image
  manifests/image.pp
Labels: bugfix

#754 Fix docker::volumes hiera example
  README.md
Labels: bugfix

#755 Add syslog_facility parameter to docker::run
  manifests/run.pp
  spec/defines/run_spec.rb
  templates/etc/systemd/system/docker-run.erb
Labels: feature

#740 Allow management of the docker-ce-cli package
  REFERENCE.md
  manifests/init.pp
  manifests/install.pp
  manifests/params.pp
  spec/classes/init_spec.rb
  spec/helper/get_defaults.rb
  spec/shared_examples/install.rb
Labels: bugfix

#746 (IAC-1613) - Update GA workflows for Nightly and PR testing
  .github/workflows/nightly.yml
  .github/workflows/pr_test.yaml
  .github/workflows/ubuntu18_pr.yaml
  spec/acceptance/compose_v3_spec.rb
Labels: maintenance
