Repository puppetlabs/puppetlabs-docker, pull requests merged in 2022-11, with the labels that each got.

#869 docker_run_flags: Shellescape any provided values
  lib/puppet/parser/functions/docker_run_flags.rb
  metadata.json
  spec/acceptance/docker_params_changed_spec.rb
  spec/unit/lib/puppet/parser/functions/docker_run_flags_spec.rb
Labels: backwards-incompatible, community

#871 (CONT-263) Bumping required puppet version
  metadata.json
Labels: backwards-incompatible

#875 Revert "(maint) Hardening manifests and tasks"
  manifests/compose.pp
  manifests/machine.pp
  manifests/plugin.pp
  manifests/registry.pp
  manifests/run.pp
  manifests/secrets.pp
  manifests/services.pp
  manifests/stack.pp
  manifests/swarm.pp
  spec/shared_examples/machine.rb
  spec/shared_examples/plugin.rb
  spec/shared_examples/registry.rb
  spec/shared_examples/run.rb
  spec/shared_examples/secrets.rb
  spec/shared_examples/services.rb
  spec/shared_examples/stack.rb
  spec/shared_examples/swarm.rb
  tasks/node_ls.rb
  tasks/node_rm.rb
  tasks/node_update.rb
  tasks/service_create.json
  tasks/service_create.rb
  tasks/service_rm.rb
  tasks/service_scale.rb
  tasks/service_update.rb
  tasks/swarm_init.rb
  tasks/swarm_join.rb
  tasks/swarm_leave.rb
  tasks/swarm_token.rb
Labels: bugfix
