Repository puppetlabs/puppetlabs-docker, pull requests merged in 2022-04, with the labels that each got.

#816 pdksync - PDKSYNC Update labeller trigger
  .github/workflows/labeller.yml
Labels: maintenance

#805 Fix idempotency when using scaling with docker-compose
  lib/puppet/provider/docker_compose/ruby.rb
  manifests/init.pp
  spec/acceptance/compose_v3_spec.rb
  spec/classes/init_spec.rb
  spec/defines/registry_spec.rb
  spec/unit/lib/puppet/type/docker_compose_spec.rb
Labels: community

#818 v4.2.0 Release prep
  CHANGELOG.md
  metadata.json
Labels: maintenance

#820 Fix permission denied issue introduced in v4.2.0
  lib/puppet/provider/docker_compose/ruby.rb
  spec/classes/init_spec.rb
  spec/defines/registry_spec.rb
  spec/unit/lib/puppet/type/docker_compose_spec.rb
Labels: bugfix

#822 Release prep for v 4.2.1
  CHANGELOG.md
  metadata.json
Labels: bugfix

#824 pdksync - (Maint) PDK Update
  .github/workflows/spec.yml
  .puppet-lint.rc
  .sync.yml
  Rakefile
  functions/sanitised_name.pp
  manifests/compose.pp
  manifests/exec.pp
  manifests/image.pp
  manifests/images.pp
  manifests/init.pp
  manifests/install.pp
  manifests/machine.pp
  manifests/networks.pp
  manifests/params.pp
  manifests/plugin.pp
  manifests/plugins.pp
  manifests/registry.pp
  manifests/registry_auth.pp
  manifests/repos.pp
  manifests/run.pp
  manifests/run_instance.pp
  manifests/secrets.pp
  manifests/service.pp
  manifests/services.pp
  manifests/stack.pp
  manifests/swarm.pp
  manifests/swarms.pp
  manifests/system_user.pp
  manifests/systemd_reload.pp
  manifests/volumes.pp
  manifests/windows_account.pp
  metadata.json
Labels: maintenance
