Repository puppetlabs/puppetlabs-docker, pull requests merged in 2022-03, with the labels that each got.

#801 pdksync - (FM-8922) - Add Support for Windows 2022
  .github/workflows/nightly.yml
  .github/workflows/pr_test.yaml
  metadata.json
  spec/acceptance/compose_v3_spec.rb
  spec/acceptance/docker_full_spec.rb
  spec/acceptance/docker_params_changed_spec.rb
  spec/spec_helper_acceptance_local.rb
Labels: feature

#807 pdksync - (GH-iac-334) Remove Support for Ubuntu 14.04/16.04
  .fixtures.yml
  .github/workflows/ubuntu18_pr.yaml
  metadata.json
Labels: bugfix

#808 (GH-iac-334) Remove code specific to unsupported OSs
  spec/acceptance/compose_v3_spec.rb
  spec/acceptance/docker_custom_source_spec.rb
  spec/acceptance/docker_full_spec.rb
  spec/acceptance/docker_spec.rb
  spec/acceptance/network_spec.rb
  spec/acceptance/plugin_spec.rb
  spec/acceptance/stack_spec.rb
  spec/acceptance/volume_spec.rb
  spec/helper/get_defaults.rb
  spec/shared_examples/params.rb
Labels: maintenance

#810 pdksync - Add labeller and stale GHA workflows
  .github/workflows/labeller.yml
  .github/workflows/stale.yml
Labels: maintenance
