Repository puppetlabs/puppetlabs-docker, pull requests merged in 2022-07, with the labels that each got.

#847 devcontainer install missing package
  .devcontainer/Dockerfile
  .devcontainer/README.md
  .devcontainer/devcontainer.json
Labels: maintenance, community

#792 Remove log_driver limitations
  manifests/init.pp
Labels: backwards-incompatible, needs-rebase, community

#846 adding optional variable for package_key_check_source to RedHat
  manifests/init.pp
Labels: community, enhancement
