Repository puppetlabs/puppetlabs-docker, pull requests merged in 2022-05, with the labels that each got.

#783 allow docker::networks::networks param to be undef
  manifests/networks.pp
  spec/classes/networks_spec.rb
Labels: bugfix, community

#787 Fix missing comma in docker::image example
  README.md
Labels: community

#802 remove some legacy facts
  manifests/params.pp
Labels: community

#826 Only install docker-ce-cli with docker-ce
  manifests/install.pp
  spec/shared_examples/install.rb
Labels: community

#827 Only install docker-ce-cli with docker-ce
  manifests/install.pp
  spec/shared_examples/install.rb
Labels: community

#823 Add tmpdir option to docker_compose
  README.md
  lib/puppet/provider/docker_compose/ruby.rb
  lib/puppet/type/docker_compose.rb
  spec/unit/lib/puppet/type/docker_compose_spec.rb
Labels: community

#832 pdksync - (MAINT) Stale bot config/msg update
  .github/workflows/stale.yml
Labels: maintenance

#833 Fix docker-compose, network and volumes not applying on 1st run, fix other idempotency
  lib/puppet/provider/docker_compose/ruby.rb
  lib/puppet/provider/docker_network/ruby.rb
  lib/puppet/provider/docker_stack/ruby.rb
  lib/puppet/provider/docker_volume/ruby.rb
  manifests/compose.pp
  manifests/params.pp
  manifests/run.pp
  manifests/service.pp
Labels: community

#837 Avoid empty array to -net parameter
  manifests/run.pp
Labels: bugfix
