Repository puppetlabs/puppetlabs-docker, pull requests merged in 2023-07, with the labels that each got.

#929 (MAINT) Fixing pipeline for Windows
  manifests/install.pp
  spec/spec_helper_acceptance_local.rb
  templates/windows/check_docker.ps1.erb
  templates/windows/check_powershell_provider.ps1.erb
  templates/windows/download_docker.ps1.erb
  templates/windows/install_powershell_provider.ps1.erb
  templates/windows/remove_docker.ps1.erb
Labels: maintenance

#935 (CONT-1196) - Remove deprecated function merge
  manifests/install.pp
Labels: bugfix

#930 (CONT-179) - Updating GitHub actions
  .github/workflows/ci.yml
  .github/workflows/nightly.yml
  spec/acceptance/compose_v3_spec.rb
  spec/acceptance/docker_spec.rb
  spec/spec_helper_acceptance_local.rb
Labels: maintenance

#939 pdksync - (CONT-1219) - fail ci for puppetlabs members if no label
  .github/workflows/labeller.yml
Labels: maintenance

#938 pdksync - (maint) - Replace legacy facts in spec/default_facts.yml
  spec/default_facts.yml
Labels: maintenance

#918 CONT-568 : Adding deferred function for password
  lib/puppet/functions/docker/env.rb
  manifests/registry.pp
  spec/functions/env_spec.rb
  templates/windows/check_hash.ps1.epp
  templates/windows/compute_hash.ps1.epp
Labels: feature
