Repository puppetlabs/puppetlabs-docker, pull requests merged in 2023-02, with the labels that each got.

#877 Use puppet yaml helper to workaround psych >4 breaking changes
  lib/puppet/provider/docker_compose/ruby.rb
Labels: community

#892 pdksync - (CONT-211) Adding mend config
  .github/workflows/mend.yml
Labels: maintenance

#897 Fix `docker` fact with recent version of docker
  lib/facter/docker.rb
  spec/unit/lib/facter/docker_spec.rb
Labels: bugfix, community
