Repository puppetlabs/puppetlabs-docker, pull requests merged in 2023-06, with the labels that each got.

#923 Fix typo in diagnostic message
  templates/windows/install_powershell_provider.ps1.erb
Labels: maintenance, community

#924 pdksync - (CONT-990) - Adding Community Pull Requests template
  .github/pull_request_template.md
Labels: maintenance

#926 (CONT-1121) - Add support for CentOS 8
  metadata.json
Labels: feature
