Repository puppetlabs/puppetlabs-docker, pull requests merged in 2024-07, with the labels that each got.

#975 Use the docker-compose-plugin via 'docker compose' instead of 'docker-compose'
  lib/puppet/provider/docker_compose/ruby.rb
  manifests/compose.pp
  manifests/params.pp
  spec/acceptance/compose_v3_spec.rb
  spec/classes/compose_spec.rb
  spec/helper/get_defaults.rb
  spec/shared_examples/compose.rb
  spec/spec_helper_acceptance_local.rb
Labels: backwards-incompatible, community

#983 systemd service overrides: restore whitespace to pre-conversion
  templates/etc/systemd/system/docker.service.d/service-overrides-debian.conf.epp
  templates/etc/systemd/system/docker.service.d/service-overrides-rhel.conf.epp
Labels: bugfix, community, bug

#986 pdksync - (CAT-1963) - Remove Labeller
  .github/workflows/labeller.yml
Labels: maintenance
